--내장함수 연습문제
SELECT ABS(-15) FROM DUAL;
SELECT CEIL(15.7) FROM DUAL;
SELECT COS(3.14159) FROM DUAL;
SELECT FLOOR(15.7) FROM DUAL;
SELECT LOG(10,100) FROM DUAL; 
SELECT MOD(11, 4) FROM DUAL;
SELECT POWER(3, 2) FROM DUAL;
SELECT ROUND(15.7) FROM DUAL;
SELECT SIGN(-15) FROM DUAL;
SELECT TRUNC(15.7) FROM DUAL;
SELECT CHR(67) FROM DUAL;
SELECT CONCAT('HAPPY ', 'Birthday') FROM DUAL;
SELECT LOWER('Birthday') FROM DUAL;
SELECT LPAD('Page 1', 15, '*.') FROM DUAL;
SELECT LTRIM('Page 1', 'ae') FROM DUAL;
SELECT REPLACE('JACK', 'J', 'BL') FROM DUAL;
SELECT RPAD('Page 1', '15', '*.') FROM DUAL;
SELECT RTRIM('Page 1', 'ae') FROM DUAL;
SELECT SUBSTR('ABCDEFG', 3, 4) FROM DUAL;
SELECT TRIM(LEADING 0 FROM '00AA00') FROM DUAL; -- LEADING 시작부분, TRAILING 끝부분, BOTH 양쪽다 
SELECT UPPER('Birthday') FROM DUAL;
SELECT ASCII('A') FROM DUAL;
SELECT INSTR('CORPORATE FLOOR', 'OR', 3, 2) FROM DUAL;
SELECT LENGTH('Birthday') FROM DUAL;
SELECT ADD_MONTHS('14/05/21', 1) FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT NEXT_DAY(SYSDATE, '화') FROM DUAL;
SELECT ROUND(SYSDATE) FROM DUAL; -- 12시 이후 반올림
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE) FROM DUAL;
SELECT TO_CHAR(123) FROM DUAL;
SELECT TO_DATE('12 05 2014', 'DD MM YYYY') FROM DUAL;
SELECT TO_NUMBER('12.3') FROM DUAL;
SELECT DECODE(1, 1, 'aa','bb') FROM DUAL; -- 조건문 DECODE(값, 조건, TRUE, FALSE)
SELECT NULLIF(123, 345) FROM DUAL; -- NULLIF(값1, 값2) : 값1과 2가 같으면 NULL, 다르면 값1을 반환
SELECT NVL(NULL, 123) FROM DUAL; -- NVL(값1, 값2) : 값1이 NULL이면 값2를 반환, NULL이 아니면 값1을 반환